### ISSUE TITLE
Capitalization Consistency 

### ISSUE THREAD

**Issue by mcawley** [geobabbler/treemap#13]
Provide consistency when capitalizing letters. Do we want to capitalize the first letter of each item?

**Comment by geobabbler** [comment]
From a quick glance, there appears to be inconsistency in both the text on the site and in some of the data (such as species). Depending on how we want to show the text, I can fix a lot of that in code.

**Comment by victography** [comment]
The capitalization in the species is intentional, per horticultural practices. The first letter of the Genus is capitalized, the first letter of species is lowercase, and any Cultivar is in Proper Case. 

As for the field names, we vote for First Letter Capitals in the popup box.

**Comment by geobabbler** [comment]
Okay. No problem. I'll correct to title case throughout the UI and let the data be data.

**Comment by victography** [comment]
Excellent, thanks.
