### ISSUE TITLE
Logo In Lower Right of Map

### ISSUE THREAD

**Issue by geobabbler** [geobabbler/treemap#4]
Display TreeBaltimore logo just above attribution banner.

**Comment by victography** [comment]
Bill with the logo I noticed that it created a fairly large transparent rectangle on the map. Is that normal? I was hoping more for this effect: 
![image](https://cloud.githubusercontent.com/assets/20578821/18359976/3db5fd78-75ca-11e6-888b-601127cd6232.png)

**Comment by geobabbler** [comment]
background now transparent
