### ISSUE TITLE
Neighborhood Filter Issues

### ISSUE THREAD

**Issue by geobabbler** [geobabbler/treemap#9]
The neighborhood filter has some issues and seems to get hung up sometimes: It doesn't show selection boundaries for some neighborhoods. If you search for text that doesn't match a name and hit enter the map doesn't do anything or tell you there's something wrong. When you hit Clear Filter it doesn't clear the search box. Couldn't get filter to work on phone, and suggested matches wouldn't list while typing name on phone.

When it selects & zooms to neighborhood, it should show only the counts for the selected neighborhood (in the Legend), the trees outside the border can stay visible (or they can disappear if you need that to happen to generate the neighborhood-only counts). Should be reset by "clear filter" button.

**Comment by geobabbler** [comment]
The problem with phone behavior may have been related to issues that were fixed when addressing IE and Safari. It seems to work okay on my iPad now. Otherwise, this issue has not been fully addressed and other unwanted behaviors may still exist.

**Comment by geobabbler** [comment]
I have the system only showing the trees in the selected neighborhood polygon. Clearing the filter causes all to draw again.

**Comment by victography** [comment]
That's excellent! Good work Bill. Everything is looking great.
